export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DISABLED_REQUEST = "USER_DISABLED_REQUEST";
export const USER_DISABLED_SUCCESS = "USER_DISABLED_SUCCESS";
export const USER_DISABLED_FAIL = "USER_DISABLED_FAIL";

export const USER_ACTIVE_REQUEST = "USER_ACTIVE_REQUEST";
export const USER_ACTIVE_SUCCESS = "USER_ACTIVE_SUCCESS";
export const USER_ACTIVE_FAIL = "USER_ACTIVE_FAIL";

export const USER_FILTERACTIVE_REQUEST = "USER_FILTERACTIVE_REQUEST";
export const USER_FILTERACTIVE_SUCCESS = "USER_FILTERACTIVE_SUCCESS";
export const USER_FILTERACTIVE_FAIL = "USER_FILTERACTIVE_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";
