export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

// ORDER FILTER NAME
export const ORDER_LISTFILTERNAME_REQUEST = "ORDER_LISTFILTERNAME_REQUEST";
export const ORDER_LISTFILTERNAME_SUCCESS = "ORDER_LISTFILTERNAME_SUCCESS";
export const ORDER_LISTFILTERNAME_FAIL = "ORDER_LISTFILTERNAME_FAIL";

// ORDER FILTER NAME
export const ORDER_LISTFILTERPAID_REQUEST = "ORDER_LISTFILTERPAID_REQUEST";
export const ORDER_LISTFILTERPAID_SUCCESS = "ORDER_LISTFILTERPAID_SUCCESS";
export const ORDER_LISTFILTERPAID_FAIL = "ORDER_LISTFILTERPAID_FAIL";

export const ORDER_LISTNOTICE_REQUEST = "ORDER_LISTNOTICE_REQUEST";
export const ORDER_LISTNOTICE_SUCCESS = "ORDER_LISTNOTICE_SUCCESS";
export const ORDER_LISTNOTICE_FAIL = "ORDER_LISTNOTICE_FAIL";

export const ORDER_LISTNOPAGINATION_REQUEST = "ORDER_LISTNOPAGINATION_REQUEST";
export const ORDER_LISTNOPAGINATION_SUCCESS = "ORDER_LISTNOPAGINATION_SUCCESS";
export const ORDER_LISTNOPAGINATION_FAIL = "ORDER_LISTNOPAGINATION_FAIL";
