export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";

export const REVIEW_DISABLED_REQUEST = "REVIEW_DISABLED_REQUEST";
export const REVIEW_DISABLED_SUCCESS = "REVIEW_DISABLED_SUCCESS";
export const REVIEW_DISABLED_FAIL = "REVIEW_DISABLED_FAIL";

export const REVIEW_ACTIVE_REQUEST = "REVIEW_ACTIVE_REQUEST";
export const REVIEW_ACTIVE_SUCCESS = "REVIEW_ACTIVE_SUCCESS";
export const REVIEW_ACTIVE_FAIL = "REVIEW_DISABLED_FAIL";
